name: Lint Hugo Theme

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install ESLint & HTMLHint
        run: |
          npm install -g eslint htmlhint

      - name: Run HTMLHint
        run: htmlhint --config .htmlhintrc layouts/**/*.html

      - name: Run ESLint
        run: eslint static/js